# -*- coding: utf-8 -*-
"""Task-01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14c9WL11437Gqh1NVAWivKcIkq70wjLxz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('/content/API_SP.POP.TOTL_DS2_en_csv_v2_5871594.csv')

# Display the first few rows of the dataset
print(df.head(4))

df.shape

# Checking missing values
df.isnull().sum()

# Handle Missing Values
df = df.fillna(method = "ffill")
df.head()

df.isnull().sum()

df.duplicated().sum()

df.drop(['Indicator Name','Indicator Code','Country Code'],axis = 1, inplace = True)

df.head()

df.columns

df = pd.DataFrame(df)
cols = [col for col in df.columns if col != 'Country Name']

cols

for i in cols:
    fig = plt.figure(figsize=(4,3))
    plt.hist(df[i],color='blue',bins=7)
    plt.xlabel(i)
    plt.ylabel('Frequency')
    plt.title(f'Histogram for {i}')
    plt.show()

# Define your columns (replace with your actual column names)
cols = ['1960','1961','1962','1963','1964','1965','1966','1967','1968','1969','1970','1971','1972','1973','1974','1975','1976','1977','1978','1979','1980','1981','1982','1983','1984', '1985','1986','1987','1988','1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022']

# Create a single figure
fig = plt.figure(figsize=(10, 6))

# Iterate over each column and plot histogram
for i in cols:
    plt.hist(df[i], bins=7, alpha=0.5, label=i)  # alpha for transparency

# Add labels and title
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.title('Combined Histogram for Multiple Columns')
plt.legend(loc='upper right')  # Add legend to distinguish between columns

# Show plot
plt.show()

country1960 = df.sort_values(by='1960').head(7)
country1960

country1960=pd.DataFrame(df)

country1960T = country1960.set_index('Country Name').T

country2022=pd.DataFrame(df)

country2022T = country2022.set_index('Country Name').T

for country_name, data_values in country2022T.iterrows():
    fig = plt.figure(figsize=(30, 15))
    sns.barplot(x=data_values.index, y=data_values.values)
    plt.xlabel('Year')
    plt.ylabel('Data Value')
    plt.title(f"{country_name} - Data Values from 1960 to 2022")
    plt.xticks(rotation=90)
    plt.show()